### ISSUE TITLE
Links to cross-origin destinations are unsafe

### ISSUE THREAD

**Issue by DavidGolodetsky** [DavidGolodetsky/GeekScore#13]
### Environment
Browsers: Chrome 
OS: Mac OS

### Steps to reproduce
Check any external link of the project. In order to see coverage you can go to Chrome Lighthouse tool and check for Best Practices option

### Expected Behaviour
Add `rel="noopener"` or `rel="noreferrer"` to any external links to improve performance and prevent security vulnerabilities.

**Comment by maruthimohan** [comment]
Hey @DavidGolodetsky , can I work on this?

**Comment by DavidGolodetsky** [comment]
Checked in Lighthouse, it's fixed. Thanx @maruthimohan!
