### ISSUE TITLE
Remove existing teams in the game from the "Select team" dropdown

### ISSUE THREAD

**Issue by DavidGolodetsky** [DavidGolodetsky/GeekScore#163]
Currently, If I already have a team in the scope of a game I can see it in the dropdown selector. Although If I try to add it won't work because this team already exists in the scope of this game.

![image](https://user-images.githubusercontent.com/32278933/135917448-3a039072-702d-4c0d-875b-9624481147b6.png)

**Expected:** Teams that already exist in the scope of this game don't appear in the dropdown.

**Acceptance Criteria:**
1. If the game already has a team with such a name, then the "Select team" dropdown shouldn't contain it.

**Comment by mgilberties** [comment]
Hi there,

Please can I have a run at this one?

Cheers,

Max

**Comment by DavidGolodetsky** [comment]
sure! good luck and thank you in advance:)
