### ISSUE TITLE
Remove white section in the bottom of the rounds table

### ISSUE THREAD

**Issue by DavidGolodetsky** [DavidGolodetsky/GeekScore#184]
**Actual:** There is a white section at the bottom of the Rounds table. 

![image](https://user-images.githubusercontent.com/32278933/137201234-b938400f-ee51-4c19-91b6-ab544fde6ad6.png)

**Expected:** It should be hidden. If it's caused by the background color of the table wrapper make it transparent

**Comment by qb-snake** [comment]
Working on this now

**Comment by qb-snake** [comment]
PR created here: https://github.com/DavidGolodetsky/GeekScore/pull/185
