### ISSUE TITLE
Show user name on the Profile page 

### ISSUE THREAD

**Issue by DavidGolodetsky** [DavidGolodetsky/GeekScore#188]
**Actual:** If the user has the username filled, it's not visible on the Profile page.

![image](https://user-images.githubusercontent.com/32278933/137624452-08feee3b-0dc6-44fd-a2c5-4527a4a6bfe1.png)

**Expected:** If the user has a username field filled, it should be visible on the Profile page.

**Tech notes:** This feature was already implemented, but currently it's not working.
You can see the username is the default name for the first player (instead of 
Me").

![image](https://user-images.githubusercontent.com/32278933/137624578-f2396644-f644-46c6-8497-76c6e018d7d2.png)

The username could be filled in manually during registration, or via Google/Facebook providers.

![image](https://user-images.githubusercontent.com/32278933/137624288-436c73f7-c0fc-427e-a0b7-a4cca8f3373a.png)

**Comment by kits4** [comment]
can you assign this to me I will try to work on this issue.

Thank You!!!!

**Comment by DavidGolodetsky** [comment]
sure, thank you too:)
